name: yolov8_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio=2.6.0
  - pytorch-cuda=12.4
  - pip
  - pip:
    - ultralytics>=8.3.0
    - pandas
    - matplotlib
    - seaborn
    - tqdm
    - pyyaml
    - ipykernel
    - opencv-python
    - scipy
